### ISSUE TITLE
Notifications / Implement logic for users (Send weekly time entry updates)

### ISSUE THREAD

**Issue by katepiliak** [CoralTime/CoralTime#136]
When the user check the checkbox "Send weekly time entry updates"  - get the value from "WEEK START ON" field and send email on this day at 1am.  
1. IF USER DOESN'T HAVE ANY HOURS FOR THE LAST WEEK PERIOD:
 Email must contain this text: 
Hello,  {{User FullName }}! It seems you haven’t filled any Time Entries for the last week. Would you like to track your time now? {{link to Calendar Page}}

Thanks for enrolling in CoralTime! 
CoralTime Team 

If you don't want to receive weekly report you can turn it off on this page (Project Settings/Preferences) {{ link to Project Setting Page }}

2. IF USER HAS REGISTERED SOME HOURS ON THE LAST WEEK:

Hello,  {{User FullName }}! You could find your hours tracked last week attached to this letter. Would you like to change your time entries now? {{link to Calendar Page}}

Thanks for enrolling in CoralTime! 
CoralTime Team 

If you don't want to receive weekly report you can turn it off on this page (Project Settings/Preferences) {{ link to Project Setting Page }}
+ ADD EXCEL FILE WITH REPORT for the last week (filtered by projects) - with all hours for all projects

**Comment by Stive-11** [comment]
done
