### ISSUE TITLE
Notifications (By Project and Weekly). Don't send email if your timer is started.

### ISSUE THREAD

**Issue by CoralTime** [CoralTime/CoralTime#212]
![image](https://user-images.githubusercontent.com/34846530/40050251-963d7da0-583f-11e8-8fc4-4b6d2c38e8bc.png)
 If I run Timer at the night - I have this email -
We need to chack if timer running now - dont send notification

**Comment by Stive-11** [comment]
Fixed in [commit](https://github.com/CoralTime/CoralTime/commit/d6885ff14a2c689abd4cc2b1c59bf035bcc2d613)
