### ISSUE TITLE
ODataUtils - useless, because there is Edm.DateTimeOffset

### ISSUE THREAD

**Issue by EdwOK** [CoralTime/CoralTime#23]
https://github.com/CoralTime/CoralTime/blob/71e64865c4446721e6730f38763e1490f2e537f6/backend/CoralTime/Serialization/ODataUtils.cs#L9-L32

**Comment by Stive-11** [comment]
It has been done in [NetCore_2.0 branch](https://github.com/CoralTime/CoralTime/tree/NetCore_2.0)
