### ISSUE TITLE
F:/B: Add action logging

### ISSUE THREAD

**Issue by katepiliak** [CoralTime/CoralTime#236]
According to our internal discussions investigate and implement on the admin page

**Comment by Stive-11** [comment]
[Front-end Application Insights](https://github.com/CoralTime/CoralTime/commit/fdc2783c7dc65be70433127234f60414aea937b8)
[Back-end Application Insights](https://github.com/CoralTime/CoralTime/commit/cd89c1fdf316869ffd79943f7563704c94827967)
