### ISSUE TITLE
Reports: Typo in tooltips.

### ISSUE THREAD

**Issue by AlexKichkailo** [CoralTime/CoralTime#270]
Should be "... Report" rather than ".. Reports", does not it? The same issue with the Send button.

![image](https://user-images.githubusercontent.com/4992307/42423743-33c40c90-8308-11e8-98c3-a1cf589537c9.png)

**Comment by Zeratulis** [comment]
I don't think so. Page called "Reports", and contains multiple grids. When we push "Send" button, we send all of them, so let it be the old title.
