### ISSUE TITLE
error in create DB 

### ISSUE THREAD

**Issue by sadiqabdali** [CoralTime/CoralTime#30]
**var cert = new X509Certificate2("coraltime.pfx", "", X509KeyStorageFlags.MachineKeySet);**

Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException HResult=0x80092009 Message=Cannot find the requested object Source=System.Security.Cryptography.X509Certificates StackTrace: at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, String password, X509KeyStorageFlags keyStorageFlags) at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags) at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags) at CoralTime.Startup.SetupIdentity(IServiceCollection services) in C:\Users\Sadiq\Downloads\CoralTime-master\CoralTime-master\backend\CoralTime\Startup.cs:line 228 at CoralTime.Startup.ConfigureServices(IServiceCollection services) in C:\Users\Sadiq\Downloads\CoralTime-master\CoralTime-master\backend\CoralTime\Startup.cs:line 107

**i receive this error when i try to create an DB and run the project**

**Comment by Stive-11** [comment]
By default, the certificate is used in the work. 
If you have it then replace the file "coraltime.pfx".
If you don't have a valid certificate then use the code below
`                services
                    .AddIdentityServer()
                    .AddTemporarySigningCredential()
                    .AddDeveloperSigningCredential()
                    .AddInMemoryIdentityResources(Config.GetIdentityResources())
                    .AddInMemoryApiResources(Config.GetApiResources())
                    .AddInMemoryClients(Config.GetClients(accessTokenLifetime, refreshTokenLifetime))
                    .AddAspNetIdentity<ApplicationUser>()
                    .AddResourceOwnerValidator<ResourceOwnerPasswordValidator>()
                    .AddProfileService<IdentityWithAdditionalClaimsProfileService>();`

**Comment by sadiqabdali** [comment]
![screenshot 36](https://user-images.githubusercontent.com/35623496/35181842-9e1749b2-fdda-11e7-984b-0df7d833abc4.png)



already is added

**Comment by Stive-11** [comment]
Maybe it needs to use password for your certificate.
https://stackoverflow.com/questions/1345262/an-internal-error-occurred-when-loading-pfx-file-with-x509certificate2
